config/routes.rb
Rails.application.routes.draw do

  root 'forecast#index'
  get 'forecast', to: 'forecast#index'

  %w(404 500).each do |code|
    get code, to: 'errors#show', code: code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def show
    render status_code.to_s, status: status_code
  end

  protected

  def status_code
    params[:code] || 500
  end
end

app/controllers/forecast_controller.rb
class ForecastController < ApplicationController
  def index
    @city = city_params[:city]
    @response = @city ? AccuweatherClient.forecast(@city) : AccuweatherClient.forecast_default
  end

  private

  def city_params
    params.permit(:city)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/forecast_helper.rb
module ForecastHelper
end

app/views/forecast/_city_forecast.html.erb
<% if forecast.empty? %>
  <h2> Ups, we couldn't find that city </h2>
<% else %>

  <div class="panel panel-default">

    <div class="panel-heading">
      <h3 class="panel-title">
        <%= city.gsub('-', ' ').split(' ').map(&:capitalize).join(' ') %>
      </h3>
    </div>

    <div class="panel-body">
        <% forecast['DailyForecasts'].each do |day_forecast| %>
          <div class="col-md-2">
            <div>
              <span class="week-day">
                <%= Date.parse(day_forecast['Date']).to_time.to_formatted_s(:week_day) %>
              </span>
              <span class="month-day">
                <%= Date.parse(day_forecast['Date']).to_time.to_formatted_s(:day_month) %>
              </span>
            </div>
            <hr />
            <%= image_tag "weather/#{day_forecast['Day']['Icon']}.png" %>
            <p>
              <span class="max-temperature">
                <%= day_forecast['Temperature']['Maximum']['Value']%> °
              </span>
              /
              <span class="min-temperature">
                <%= day_forecast['Temperature']['Minimum']['Value']%> °
              </span>
            </p>
            <p>
              <%= day_forecast['Day']['IconPhrase'] %>
            </p>
            <br />
          </div>
      <% end %>
    </div>

  </div>
<% end %>

app/views/forecast/index.html.erb
<div class="container">
  <% @response.each do |city, forecast| %>
    <div class="row">
      <%= render 'city_forecast', city: city, forecast: forecast %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AcidForecast</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Acid forecast</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/?city=Paris">Paris</a></li>
        <li><a href="/?city=Bangkok">Bangkok</a></li>
        <li><a href="/?city=Santiago">Santiago</a></li>
        <li><a href="/?city=New-York">New York</a></li>
        <li><a href="/?city=Bamako">Bamako</a></li>
      </ul>
      <%= form_tag forecast_path, method: 'get', class: "navbar-form navbar-left" do %>
        <div class="form-group">
          <%= text_field_tag :city, '', placeholder: 'City', class: "form-control" %>
        </div>
        <%= submit_tag 'Search', name: nil, class: "btn btn-default" %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%= yield %>

</body>
</html>